export const adminSchemas = [
  { value: "public", label: "public (ortak)" },
  { value: "kamubase", label: "kamubase" },
  { value: "sourcebase", label: "sourcebase" },
  { value: "praticase", label: "praticase" },
] as const;

export type AdminSchema = (typeof adminSchemas)[number]["value"];

export const appHealthTargets = [
  { name: "Ortak Supabase", url: "https://medasi.com.tr", group: "Altyapi" },
  { name: "Qlinik", url: "https://qlinik.medasi.com.tr", group: "Uygulama" },
  { name: "PratiCase", url: "https://praticase.medasi.com.tr", group: "Uygulama" },
  { name: "SourceBase", url: "https://sourcebase.medasi.com.tr", group: "Uygulama" },
  { name: "MedAsiPay", url: "https://odeme.medasi.com.tr", group: "Odeme" },
  { name: "Indirme", url: "https://indir.medasi.com.tr", group: "Dagitim" },
  { name: "Destek", url: "https://destek.medasi.com.tr", group: "Destek" },
] as const;

export const tableShortcuts: Record<AdminSchema, string[]> = {
  public: [
    "profiles",
    "user_roles",
    "store_products",
    "purchases",
    "wallet_entitlements",
    "wallet_transactions",
    "gift_codes",
    "gift_code_redemptions",
    "ai_usage_events",
    "questions",
    "qlinik_taxonomy",
    "question_attempts",
    "question_deliveries",
    "user_solved_questions",
    "spot_facts",
    "notification_messages",
    "notification_deliveries",
    "push_device_tokens",
    "admin_action_logs",
    "medasi_learning_attempt_facts",
    "medasi_learning_gap_rollups",
  ],
  kamubase: [
    "topic_tree",
    "questions",
    "question_attempts",
    "question_deliveries",
    "user_solved_questions",
    "medasi_learning_attempt_facts",
    "medasi_learning_gap_rollups",
  ],
  sourcebase: [
    "courses",
    "sections",
    "drive_files",
    "sources",
    "decks",
    "cards",
    "generated_jobs",
    "generated_outputs",
    "products",
    "product_decks",
    "purchases",
    "entitlements",
    "study_sessions",
    "study_progress",
    "app_memberships",
    "storage_roots",
    "wallet_transactions",
    "audit_logs",
    "support_tickets",
    "candidate_questions",
  ],
  praticase: [
    "cases",
    "god_mode_case_publication_v",
    "god_mode_content_health_v",
    "home_banners",
    "badge_definitions",
    "support_topics",
    "faq_items",
    "announcements",
    "notification_campaigns",
    "contact_requests",
    "medication_infos",
    "case_patient_response_rules",
    "physical_exam_groups",
    "physical_exam_options",
    "test_groups",
    "test_options",
    "diagnosis_options",
    "management_plan_options",
    "lab_result_details",
    "imaging_result_details",
    "exam_sessions",
    "exam_messages",
    "session_physical_exam_findings",
    "session_requested_tests",
    "session_diagnosis_answers",
    "session_management_plan_items",
    "session_management_notes",
    "session_result_summaries",
    "user_dashboard_stats",
    "user_case_progress",
    "user_bookmarked_cases",
    "user_notes",
    "praticase_history_checklists",
    "praticase_physical_exam_checklists",
    "praticase_laboratory_checklists",
    "praticase_imaging_checklists",
    "praticase_diagnostic_checklists",
  ],
};

export const serviceChecks = [
  { id: "db", label: "Supabase DB ping", schema: "public", table: "profiles" },
  { id: "profiles", label: "count public.profiles", schema: "public", table: "profiles" },
  { id: "questions", label: "count public.questions", schema: "public", table: "questions" },
  { id: "kamubase", label: "count kamubase.questions", schema: "kamubase", table: "questions" },
  {
    id: "jobs",
    label: "count sourcebase.generated_jobs",
    schema: "sourcebase",
    table: "generated_jobs",
  },
  { id: "cases", label: "count praticase.cases", schema: "praticase", table: "cases" },
  {
    id: "health",
    label: "count praticase.god_mode_content_health_v",
    schema: "praticase",
    table: "god_mode_content_health_v",
  },
] as const;
