/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NoAccessRouteImport } from './routes/no-access'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiQlinikPdfRouteImport } from './routes/api/qlinik-pdf'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminVeriGezginiRouteImport } from './routes/_authenticated/admin/veri-gezgini'
import { Route as AuthenticatedAdminVakalarRouteImport } from './routes/_authenticated/admin/vakalar'
import { Route as AuthenticatedAdminVakaUretimRouteImport } from './routes/_authenticated/admin/vaka-uretim'
import { Route as AuthenticatedAdminTopluUretimRouteImport } from './routes/_authenticated/admin/toplu-uretim'
import { Route as AuthenticatedAdminSourcebaseRouteImport } from './routes/_authenticated/admin/sourcebase'
import { Route as AuthenticatedAdminServisSagligiRouteImport } from './routes/_authenticated/admin/servis-sagligi'
import { Route as AuthenticatedAdminSatinAlmalarRouteImport } from './routes/_authenticated/admin/satin-almalar'
import { Route as AuthenticatedAdminRecallRouteImport } from './routes/_authenticated/admin/recall'
import { Route as AuthenticatedAdminQlinikRouteImport } from './routes/_authenticated/admin/qlinik'
import { Route as AuthenticatedAdminPromptsRouteImport } from './routes/_authenticated/admin/prompts'
import { Route as AuthenticatedAdminPraticaseRouteImport } from './routes/_authenticated/admin/praticase'
import { Route as AuthenticatedAdminPdfCiktiRouteImport } from './routes/_authenticated/admin/pdf-cikti'
import { Route as AuthenticatedAdminMedasipayRouteImport } from './routes/_authenticated/admin/medasipay'
import { Route as AuthenticatedAdminMarketingRouteImport } from './routes/_authenticated/admin/marketing'
import { Route as AuthenticatedAdminKullanicilarRouteImport } from './routes/_authenticated/admin/kullanicilar'
import { Route as AuthenticatedAdminKaynaklarRouteImport } from './routes/_authenticated/admin/kaynaklar'
import { Route as AuthenticatedAdminJobQueueRouteImport } from './routes/_authenticated/admin/job-queue'
import { Route as AuthenticatedAdminIstatistikRouteImport } from './routes/_authenticated/admin/istatistik'
import { Route as AuthenticatedAdminIndirmeRouteImport } from './routes/_authenticated/admin/indirme'
import { Route as AuthenticatedAdminIcerikSagligiRouteImport } from './routes/_authenticated/admin/icerik-sagligi'
import { Route as AuthenticatedAdminIceAktarRouteImport } from './routes/_authenticated/admin/ice-aktar'
import { Route as AuthenticatedAdminGenelBakisRouteImport } from './routes/_authenticated/admin/genel-bakis'
import { Route as AuthenticatedAdminDestekRouteImport } from './routes/_authenticated/admin/destek'
import { Route as AuthenticatedAdminCuzdanRouteImport } from './routes/_authenticated/admin/cuzdan'
import { Route as AuthenticatedAdminBildirimlerRouteImport } from './routes/_authenticated/admin/bildirimler'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin/audit'
import { Route as AuthenticatedAdminAiStudioRouteImport } from './routes/_authenticated/admin/ai-studio'
import { Route as AuthenticatedAdminAiMaliyetleriRouteImport } from './routes/_authenticated/admin/ai-maliyetleri'

const NoAccessRoute = NoAccessRouteImport.update({
  id: '/no-access',
  path: '/no-access',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQlinikPdfRoute = ApiQlinikPdfRouteImport.update({
  id: '/api/qlinik-pdf',
  path: '/api/qlinik-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminVeriGezginiRoute =
  AuthenticatedAdminVeriGezginiRouteImport.update({
    id: '/veri-gezgini',
    path: '/veri-gezgini',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminVakalarRoute =
  AuthenticatedAdminVakalarRouteImport.update({
    id: '/vakalar',
    path: '/vakalar',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminVakaUretimRoute =
  AuthenticatedAdminVakaUretimRouteImport.update({
    id: '/vaka-uretim',
    path: '/vaka-uretim',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTopluUretimRoute =
  AuthenticatedAdminTopluUretimRouteImport.update({
    id: '/toplu-uretim',
    path: '/toplu-uretim',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSourcebaseRoute =
  AuthenticatedAdminSourcebaseRouteImport.update({
    id: '/sourcebase',
    path: '/sourcebase',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminServisSagligiRoute =
  AuthenticatedAdminServisSagligiRouteImport.update({
    id: '/servis-sagligi',
    path: '/servis-sagligi',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSatinAlmalarRoute =
  AuthenticatedAdminSatinAlmalarRouteImport.update({
    id: '/satin-almalar',
    path: '/satin-almalar',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRecallRoute =
  AuthenticatedAdminRecallRouteImport.update({
    id: '/recall',
    path: '/recall',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminQlinikRoute =
  AuthenticatedAdminQlinikRouteImport.update({
    id: '/qlinik',
    path: '/qlinik',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPromptsRoute =
  AuthenticatedAdminPromptsRouteImport.update({
    id: '/prompts',
    path: '/prompts',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPraticaseRoute =
  AuthenticatedAdminPraticaseRouteImport.update({
    id: '/praticase',
    path: '/praticase',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPdfCiktiRoute =
  AuthenticatedAdminPdfCiktiRouteImport.update({
    id: '/pdf-cikti',
    path: '/pdf-cikti',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMedasipayRoute =
  AuthenticatedAdminMedasipayRouteImport.update({
    id: '/medasipay',
    path: '/medasipay',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMarketingRoute =
  AuthenticatedAdminMarketingRouteImport.update({
    id: '/marketing',
    path: '/marketing',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminKullanicilarRoute =
  AuthenticatedAdminKullanicilarRouteImport.update({
    id: '/kullanicilar',
    path: '/kullanicilar',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminKaynaklarRoute =
  AuthenticatedAdminKaynaklarRouteImport.update({
    id: '/kaynaklar',
    path: '/kaynaklar',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminJobQueueRoute =
  AuthenticatedAdminJobQueueRouteImport.update({
    id: '/job-queue',
    path: '/job-queue',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminIstatistikRoute =
  AuthenticatedAdminIstatistikRouteImport.update({
    id: '/istatistik',
    path: '/istatistik',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminIndirmeRoute =
  AuthenticatedAdminIndirmeRouteImport.update({
    id: '/indirme',
    path: '/indirme',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminIcerikSagligiRoute =
  AuthenticatedAdminIcerikSagligiRouteImport.update({
    id: '/icerik-sagligi',
    path: '/icerik-sagligi',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminIceAktarRoute =
  AuthenticatedAdminIceAktarRouteImport.update({
    id: '/ice-aktar',
    path: '/ice-aktar',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminGenelBakisRoute =
  AuthenticatedAdminGenelBakisRouteImport.update({
    id: '/genel-bakis',
    path: '/genel-bakis',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDestekRoute =
  AuthenticatedAdminDestekRouteImport.update({
    id: '/destek',
    path: '/destek',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCuzdanRoute =
  AuthenticatedAdminCuzdanRouteImport.update({
    id: '/cuzdan',
    path: '/cuzdan',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBildirimlerRoute =
  AuthenticatedAdminBildirimlerRouteImport.update({
    id: '/bildirimler',
    path: '/bildirimler',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAiStudioRoute =
  AuthenticatedAdminAiStudioRouteImport.update({
    id: '/ai-studio',
    path: '/ai-studio',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAiMaliyetleriRoute =
  AuthenticatedAdminAiMaliyetleriRouteImport.update({
    id: '/ai-maliyetleri',
    path: '/ai-maliyetleri',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/no-access': typeof NoAccessRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/api/qlinik-pdf': typeof ApiQlinikPdfRoute
  '/admin/ai-maliyetleri': typeof AuthenticatedAdminAiMaliyetleriRoute
  '/admin/ai-studio': typeof AuthenticatedAdminAiStudioRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/bildirimler': typeof AuthenticatedAdminBildirimlerRoute
  '/admin/cuzdan': typeof AuthenticatedAdminCuzdanRoute
  '/admin/destek': typeof AuthenticatedAdminDestekRoute
  '/admin/genel-bakis': typeof AuthenticatedAdminGenelBakisRoute
  '/admin/ice-aktar': typeof AuthenticatedAdminIceAktarRoute
  '/admin/icerik-sagligi': typeof AuthenticatedAdminIcerikSagligiRoute
  '/admin/indirme': typeof AuthenticatedAdminIndirmeRoute
  '/admin/istatistik': typeof AuthenticatedAdminIstatistikRoute
  '/admin/job-queue': typeof AuthenticatedAdminJobQueueRoute
  '/admin/kaynaklar': typeof AuthenticatedAdminKaynaklarRoute
  '/admin/kullanicilar': typeof AuthenticatedAdminKullanicilarRoute
  '/admin/marketing': typeof AuthenticatedAdminMarketingRoute
  '/admin/medasipay': typeof AuthenticatedAdminMedasipayRoute
  '/admin/pdf-cikti': typeof AuthenticatedAdminPdfCiktiRoute
  '/admin/praticase': typeof AuthenticatedAdminPraticaseRoute
  '/admin/prompts': typeof AuthenticatedAdminPromptsRoute
  '/admin/qlinik': typeof AuthenticatedAdminQlinikRoute
  '/admin/recall': typeof AuthenticatedAdminRecallRoute
  '/admin/satin-almalar': typeof AuthenticatedAdminSatinAlmalarRoute
  '/admin/servis-sagligi': typeof AuthenticatedAdminServisSagligiRoute
  '/admin/sourcebase': typeof AuthenticatedAdminSourcebaseRoute
  '/admin/toplu-uretim': typeof AuthenticatedAdminTopluUretimRoute
  '/admin/vaka-uretim': typeof AuthenticatedAdminVakaUretimRoute
  '/admin/vakalar': typeof AuthenticatedAdminVakalarRoute
  '/admin/veri-gezgini': typeof AuthenticatedAdminVeriGezginiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/no-access': typeof NoAccessRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/api/qlinik-pdf': typeof ApiQlinikPdfRoute
  '/admin/ai-maliyetleri': typeof AuthenticatedAdminAiMaliyetleriRoute
  '/admin/ai-studio': typeof AuthenticatedAdminAiStudioRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/bildirimler': typeof AuthenticatedAdminBildirimlerRoute
  '/admin/cuzdan': typeof AuthenticatedAdminCuzdanRoute
  '/admin/destek': typeof AuthenticatedAdminDestekRoute
  '/admin/genel-bakis': typeof AuthenticatedAdminGenelBakisRoute
  '/admin/ice-aktar': typeof AuthenticatedAdminIceAktarRoute
  '/admin/icerik-sagligi': typeof AuthenticatedAdminIcerikSagligiRoute
  '/admin/indirme': typeof AuthenticatedAdminIndirmeRoute
  '/admin/istatistik': typeof AuthenticatedAdminIstatistikRoute
  '/admin/job-queue': typeof AuthenticatedAdminJobQueueRoute
  '/admin/kaynaklar': typeof AuthenticatedAdminKaynaklarRoute
  '/admin/kullanicilar': typeof AuthenticatedAdminKullanicilarRoute
  '/admin/marketing': typeof AuthenticatedAdminMarketingRoute
  '/admin/medasipay': typeof AuthenticatedAdminMedasipayRoute
  '/admin/pdf-cikti': typeof AuthenticatedAdminPdfCiktiRoute
  '/admin/praticase': typeof AuthenticatedAdminPraticaseRoute
  '/admin/prompts': typeof AuthenticatedAdminPromptsRoute
  '/admin/qlinik': typeof AuthenticatedAdminQlinikRoute
  '/admin/recall': typeof AuthenticatedAdminRecallRoute
  '/admin/satin-almalar': typeof AuthenticatedAdminSatinAlmalarRoute
  '/admin/servis-sagligi': typeof AuthenticatedAdminServisSagligiRoute
  '/admin/sourcebase': typeof AuthenticatedAdminSourcebaseRoute
  '/admin/toplu-uretim': typeof AuthenticatedAdminTopluUretimRoute
  '/admin/vaka-uretim': typeof AuthenticatedAdminVakaUretimRoute
  '/admin/vakalar': typeof AuthenticatedAdminVakalarRoute
  '/admin/veri-gezgini': typeof AuthenticatedAdminVeriGezginiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/no-access': typeof NoAccessRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/api/qlinik-pdf': typeof ApiQlinikPdfRoute
  '/_authenticated/admin/ai-maliyetleri': typeof AuthenticatedAdminAiMaliyetleriRoute
  '/_authenticated/admin/ai-studio': typeof AuthenticatedAdminAiStudioRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/bildirimler': typeof AuthenticatedAdminBildirimlerRoute
  '/_authenticated/admin/cuzdan': typeof AuthenticatedAdminCuzdanRoute
  '/_authenticated/admin/destek': typeof AuthenticatedAdminDestekRoute
  '/_authenticated/admin/genel-bakis': typeof AuthenticatedAdminGenelBakisRoute
  '/_authenticated/admin/ice-aktar': typeof AuthenticatedAdminIceAktarRoute
  '/_authenticated/admin/icerik-sagligi': typeof AuthenticatedAdminIcerikSagligiRoute
  '/_authenticated/admin/indirme': typeof AuthenticatedAdminIndirmeRoute
  '/_authenticated/admin/istatistik': typeof AuthenticatedAdminIstatistikRoute
  '/_authenticated/admin/job-queue': typeof AuthenticatedAdminJobQueueRoute
  '/_authenticated/admin/kaynaklar': typeof AuthenticatedAdminKaynaklarRoute
  '/_authenticated/admin/kullanicilar': typeof AuthenticatedAdminKullanicilarRoute
  '/_authenticated/admin/marketing': typeof AuthenticatedAdminMarketingRoute
  '/_authenticated/admin/medasipay': typeof AuthenticatedAdminMedasipayRoute
  '/_authenticated/admin/pdf-cikti': typeof AuthenticatedAdminPdfCiktiRoute
  '/_authenticated/admin/praticase': typeof AuthenticatedAdminPraticaseRoute
  '/_authenticated/admin/prompts': typeof AuthenticatedAdminPromptsRoute
  '/_authenticated/admin/qlinik': typeof AuthenticatedAdminQlinikRoute
  '/_authenticated/admin/recall': typeof AuthenticatedAdminRecallRoute
  '/_authenticated/admin/satin-almalar': typeof AuthenticatedAdminSatinAlmalarRoute
  '/_authenticated/admin/servis-sagligi': typeof AuthenticatedAdminServisSagligiRoute
  '/_authenticated/admin/sourcebase': typeof AuthenticatedAdminSourcebaseRoute
  '/_authenticated/admin/toplu-uretim': typeof AuthenticatedAdminTopluUretimRoute
  '/_authenticated/admin/vaka-uretim': typeof AuthenticatedAdminVakaUretimRoute
  '/_authenticated/admin/vakalar': typeof AuthenticatedAdminVakalarRoute
  '/_authenticated/admin/veri-gezgini': typeof AuthenticatedAdminVeriGezginiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/no-access'
    | '/admin'
    | '/api/qlinik-pdf'
    | '/admin/ai-maliyetleri'
    | '/admin/ai-studio'
    | '/admin/audit'
    | '/admin/bildirimler'
    | '/admin/cuzdan'
    | '/admin/destek'
    | '/admin/genel-bakis'
    | '/admin/ice-aktar'
    | '/admin/icerik-sagligi'
    | '/admin/indirme'
    | '/admin/istatistik'
    | '/admin/job-queue'
    | '/admin/kaynaklar'
    | '/admin/kullanicilar'
    | '/admin/marketing'
    | '/admin/medasipay'
    | '/admin/pdf-cikti'
    | '/admin/praticase'
    | '/admin/prompts'
    | '/admin/qlinik'
    | '/admin/recall'
    | '/admin/satin-almalar'
    | '/admin/servis-sagligi'
    | '/admin/sourcebase'
    | '/admin/toplu-uretim'
    | '/admin/vaka-uretim'
    | '/admin/vakalar'
    | '/admin/veri-gezgini'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/no-access'
    | '/admin'
    | '/api/qlinik-pdf'
    | '/admin/ai-maliyetleri'
    | '/admin/ai-studio'
    | '/admin/audit'
    | '/admin/bildirimler'
    | '/admin/cuzdan'
    | '/admin/destek'
    | '/admin/genel-bakis'
    | '/admin/ice-aktar'
    | '/admin/icerik-sagligi'
    | '/admin/indirme'
    | '/admin/istatistik'
    | '/admin/job-queue'
    | '/admin/kaynaklar'
    | '/admin/kullanicilar'
    | '/admin/marketing'
    | '/admin/medasipay'
    | '/admin/pdf-cikti'
    | '/admin/praticase'
    | '/admin/prompts'
    | '/admin/qlinik'
    | '/admin/recall'
    | '/admin/satin-almalar'
    | '/admin/servis-sagligi'
    | '/admin/sourcebase'
    | '/admin/toplu-uretim'
    | '/admin/vaka-uretim'
    | '/admin/vakalar'
    | '/admin/veri-gezgini'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/no-access'
    | '/_authenticated/admin'
    | '/api/qlinik-pdf'
    | '/_authenticated/admin/ai-maliyetleri'
    | '/_authenticated/admin/ai-studio'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/bildirimler'
    | '/_authenticated/admin/cuzdan'
    | '/_authenticated/admin/destek'
    | '/_authenticated/admin/genel-bakis'
    | '/_authenticated/admin/ice-aktar'
    | '/_authenticated/admin/icerik-sagligi'
    | '/_authenticated/admin/indirme'
    | '/_authenticated/admin/istatistik'
    | '/_authenticated/admin/job-queue'
    | '/_authenticated/admin/kaynaklar'
    | '/_authenticated/admin/kullanicilar'
    | '/_authenticated/admin/marketing'
    | '/_authenticated/admin/medasipay'
    | '/_authenticated/admin/pdf-cikti'
    | '/_authenticated/admin/praticase'
    | '/_authenticated/admin/prompts'
    | '/_authenticated/admin/qlinik'
    | '/_authenticated/admin/recall'
    | '/_authenticated/admin/satin-almalar'
    | '/_authenticated/admin/servis-sagligi'
    | '/_authenticated/admin/sourcebase'
    | '/_authenticated/admin/toplu-uretim'
    | '/_authenticated/admin/vaka-uretim'
    | '/_authenticated/admin/vakalar'
    | '/_authenticated/admin/veri-gezgini'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  NoAccessRoute: typeof NoAccessRoute
  ApiQlinikPdfRoute: typeof ApiQlinikPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/no-access': {
      id: '/no-access'
      path: '/no-access'
      fullPath: '/no-access'
      preLoaderRoute: typeof NoAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/qlinik-pdf': {
      id: '/api/qlinik-pdf'
      path: '/api/qlinik-pdf'
      fullPath: '/api/qlinik-pdf'
      preLoaderRoute: typeof ApiQlinikPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/veri-gezgini': {
      id: '/_authenticated/admin/veri-gezgini'
      path: '/veri-gezgini'
      fullPath: '/admin/veri-gezgini'
      preLoaderRoute: typeof AuthenticatedAdminVeriGezginiRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/vakalar': {
      id: '/_authenticated/admin/vakalar'
      path: '/vakalar'
      fullPath: '/admin/vakalar'
      preLoaderRoute: typeof AuthenticatedAdminVakalarRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/vaka-uretim': {
      id: '/_authenticated/admin/vaka-uretim'
      path: '/vaka-uretim'
      fullPath: '/admin/vaka-uretim'
      preLoaderRoute: typeof AuthenticatedAdminVakaUretimRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/toplu-uretim': {
      id: '/_authenticated/admin/toplu-uretim'
      path: '/toplu-uretim'
      fullPath: '/admin/toplu-uretim'
      preLoaderRoute: typeof AuthenticatedAdminTopluUretimRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/sourcebase': {
      id: '/_authenticated/admin/sourcebase'
      path: '/sourcebase'
      fullPath: '/admin/sourcebase'
      preLoaderRoute: typeof AuthenticatedAdminSourcebaseRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/servis-sagligi': {
      id: '/_authenticated/admin/servis-sagligi'
      path: '/servis-sagligi'
      fullPath: '/admin/servis-sagligi'
      preLoaderRoute: typeof AuthenticatedAdminServisSagligiRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/satin-almalar': {
      id: '/_authenticated/admin/satin-almalar'
      path: '/satin-almalar'
      fullPath: '/admin/satin-almalar'
      preLoaderRoute: typeof AuthenticatedAdminSatinAlmalarRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/recall': {
      id: '/_authenticated/admin/recall'
      path: '/recall'
      fullPath: '/admin/recall'
      preLoaderRoute: typeof AuthenticatedAdminRecallRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/qlinik': {
      id: '/_authenticated/admin/qlinik'
      path: '/qlinik'
      fullPath: '/admin/qlinik'
      preLoaderRoute: typeof AuthenticatedAdminQlinikRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/prompts': {
      id: '/_authenticated/admin/prompts'
      path: '/prompts'
      fullPath: '/admin/prompts'
      preLoaderRoute: typeof AuthenticatedAdminPromptsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/praticase': {
      id: '/_authenticated/admin/praticase'
      path: '/praticase'
      fullPath: '/admin/praticase'
      preLoaderRoute: typeof AuthenticatedAdminPraticaseRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/pdf-cikti': {
      id: '/_authenticated/admin/pdf-cikti'
      path: '/pdf-cikti'
      fullPath: '/admin/pdf-cikti'
      preLoaderRoute: typeof AuthenticatedAdminPdfCiktiRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/medasipay': {
      id: '/_authenticated/admin/medasipay'
      path: '/medasipay'
      fullPath: '/admin/medasipay'
      preLoaderRoute: typeof AuthenticatedAdminMedasipayRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/marketing': {
      id: '/_authenticated/admin/marketing'
      path: '/marketing'
      fullPath: '/admin/marketing'
      preLoaderRoute: typeof AuthenticatedAdminMarketingRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/kullanicilar': {
      id: '/_authenticated/admin/kullanicilar'
      path: '/kullanicilar'
      fullPath: '/admin/kullanicilar'
      preLoaderRoute: typeof AuthenticatedAdminKullanicilarRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/kaynaklar': {
      id: '/_authenticated/admin/kaynaklar'
      path: '/kaynaklar'
      fullPath: '/admin/kaynaklar'
      preLoaderRoute: typeof AuthenticatedAdminKaynaklarRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/job-queue': {
      id: '/_authenticated/admin/job-queue'
      path: '/job-queue'
      fullPath: '/admin/job-queue'
      preLoaderRoute: typeof AuthenticatedAdminJobQueueRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/istatistik': {
      id: '/_authenticated/admin/istatistik'
      path: '/istatistik'
      fullPath: '/admin/istatistik'
      preLoaderRoute: typeof AuthenticatedAdminIstatistikRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/indirme': {
      id: '/_authenticated/admin/indirme'
      path: '/indirme'
      fullPath: '/admin/indirme'
      preLoaderRoute: typeof AuthenticatedAdminIndirmeRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/icerik-sagligi': {
      id: '/_authenticated/admin/icerik-sagligi'
      path: '/icerik-sagligi'
      fullPath: '/admin/icerik-sagligi'
      preLoaderRoute: typeof AuthenticatedAdminIcerikSagligiRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/ice-aktar': {
      id: '/_authenticated/admin/ice-aktar'
      path: '/ice-aktar'
      fullPath: '/admin/ice-aktar'
      preLoaderRoute: typeof AuthenticatedAdminIceAktarRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/genel-bakis': {
      id: '/_authenticated/admin/genel-bakis'
      path: '/genel-bakis'
      fullPath: '/admin/genel-bakis'
      preLoaderRoute: typeof AuthenticatedAdminGenelBakisRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/destek': {
      id: '/_authenticated/admin/destek'
      path: '/destek'
      fullPath: '/admin/destek'
      preLoaderRoute: typeof AuthenticatedAdminDestekRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cuzdan': {
      id: '/_authenticated/admin/cuzdan'
      path: '/cuzdan'
      fullPath: '/admin/cuzdan'
      preLoaderRoute: typeof AuthenticatedAdminCuzdanRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/bildirimler': {
      id: '/_authenticated/admin/bildirimler'
      path: '/bildirimler'
      fullPath: '/admin/bildirimler'
      preLoaderRoute: typeof AuthenticatedAdminBildirimlerRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/ai-studio': {
      id: '/_authenticated/admin/ai-studio'
      path: '/ai-studio'
      fullPath: '/admin/ai-studio'
      preLoaderRoute: typeof AuthenticatedAdminAiStudioRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/ai-maliyetleri': {
      id: '/_authenticated/admin/ai-maliyetleri'
      path: '/ai-maliyetleri'
      fullPath: '/admin/ai-maliyetleri'
      preLoaderRoute: typeof AuthenticatedAdminAiMaliyetleriRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAiMaliyetleriRoute: typeof AuthenticatedAdminAiMaliyetleriRoute
  AuthenticatedAdminAiStudioRoute: typeof AuthenticatedAdminAiStudioRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminBildirimlerRoute: typeof AuthenticatedAdminBildirimlerRoute
  AuthenticatedAdminCuzdanRoute: typeof AuthenticatedAdminCuzdanRoute
  AuthenticatedAdminDestekRoute: typeof AuthenticatedAdminDestekRoute
  AuthenticatedAdminGenelBakisRoute: typeof AuthenticatedAdminGenelBakisRoute
  AuthenticatedAdminIceAktarRoute: typeof AuthenticatedAdminIceAktarRoute
  AuthenticatedAdminIcerikSagligiRoute: typeof AuthenticatedAdminIcerikSagligiRoute
  AuthenticatedAdminIndirmeRoute: typeof AuthenticatedAdminIndirmeRoute
  AuthenticatedAdminIstatistikRoute: typeof AuthenticatedAdminIstatistikRoute
  AuthenticatedAdminJobQueueRoute: typeof AuthenticatedAdminJobQueueRoute
  AuthenticatedAdminKaynaklarRoute: typeof AuthenticatedAdminKaynaklarRoute
  AuthenticatedAdminKullanicilarRoute: typeof AuthenticatedAdminKullanicilarRoute
  AuthenticatedAdminMarketingRoute: typeof AuthenticatedAdminMarketingRoute
  AuthenticatedAdminMedasipayRoute: typeof AuthenticatedAdminMedasipayRoute
  AuthenticatedAdminPdfCiktiRoute: typeof AuthenticatedAdminPdfCiktiRoute
  AuthenticatedAdminPraticaseRoute: typeof AuthenticatedAdminPraticaseRoute
  AuthenticatedAdminPromptsRoute: typeof AuthenticatedAdminPromptsRoute
  AuthenticatedAdminQlinikRoute: typeof AuthenticatedAdminQlinikRoute
  AuthenticatedAdminRecallRoute: typeof AuthenticatedAdminRecallRoute
  AuthenticatedAdminSatinAlmalarRoute: typeof AuthenticatedAdminSatinAlmalarRoute
  AuthenticatedAdminServisSagligiRoute: typeof AuthenticatedAdminServisSagligiRoute
  AuthenticatedAdminSourcebaseRoute: typeof AuthenticatedAdminSourcebaseRoute
  AuthenticatedAdminTopluUretimRoute: typeof AuthenticatedAdminTopluUretimRoute
  AuthenticatedAdminVakaUretimRoute: typeof AuthenticatedAdminVakaUretimRoute
  AuthenticatedAdminVakalarRoute: typeof AuthenticatedAdminVakalarRoute
  AuthenticatedAdminVeriGezginiRoute: typeof AuthenticatedAdminVeriGezginiRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAiMaliyetleriRoute: AuthenticatedAdminAiMaliyetleriRoute,
    AuthenticatedAdminAiStudioRoute: AuthenticatedAdminAiStudioRoute,
    AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
    AuthenticatedAdminBildirimlerRoute: AuthenticatedAdminBildirimlerRoute,
    AuthenticatedAdminCuzdanRoute: AuthenticatedAdminCuzdanRoute,
    AuthenticatedAdminDestekRoute: AuthenticatedAdminDestekRoute,
    AuthenticatedAdminGenelBakisRoute: AuthenticatedAdminGenelBakisRoute,
    AuthenticatedAdminIceAktarRoute: AuthenticatedAdminIceAktarRoute,
    AuthenticatedAdminIcerikSagligiRoute: AuthenticatedAdminIcerikSagligiRoute,
    AuthenticatedAdminIndirmeRoute: AuthenticatedAdminIndirmeRoute,
    AuthenticatedAdminIstatistikRoute: AuthenticatedAdminIstatistikRoute,
    AuthenticatedAdminJobQueueRoute: AuthenticatedAdminJobQueueRoute,
    AuthenticatedAdminKaynaklarRoute: AuthenticatedAdminKaynaklarRoute,
    AuthenticatedAdminKullanicilarRoute: AuthenticatedAdminKullanicilarRoute,
    AuthenticatedAdminMarketingRoute: AuthenticatedAdminMarketingRoute,
    AuthenticatedAdminMedasipayRoute: AuthenticatedAdminMedasipayRoute,
    AuthenticatedAdminPdfCiktiRoute: AuthenticatedAdminPdfCiktiRoute,
    AuthenticatedAdminPraticaseRoute: AuthenticatedAdminPraticaseRoute,
    AuthenticatedAdminPromptsRoute: AuthenticatedAdminPromptsRoute,
    AuthenticatedAdminQlinikRoute: AuthenticatedAdminQlinikRoute,
    AuthenticatedAdminRecallRoute: AuthenticatedAdminRecallRoute,
    AuthenticatedAdminSatinAlmalarRoute: AuthenticatedAdminSatinAlmalarRoute,
    AuthenticatedAdminServisSagligiRoute: AuthenticatedAdminServisSagligiRoute,
    AuthenticatedAdminSourcebaseRoute: AuthenticatedAdminSourcebaseRoute,
    AuthenticatedAdminTopluUretimRoute: AuthenticatedAdminTopluUretimRoute,
    AuthenticatedAdminVakaUretimRoute: AuthenticatedAdminVakaUretimRoute,
    AuthenticatedAdminVakalarRoute: AuthenticatedAdminVakalarRoute,
    AuthenticatedAdminVeriGezginiRoute: AuthenticatedAdminVeriGezginiRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  NoAccessRoute: NoAccessRoute,
  ApiQlinikPdfRoute: ApiQlinikPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
