-- 20260621170000 Qlinik: FTR + Veteriner disiplinleri + veteriner taksonomisi (VUÇEP-2021)
-- Bu migration self-hosted Supabase'de uygulanmalı (Supabase Studio > SQL Editor veya psql).

-- 1) Disiplin whitelist'ine ftr + veteriner ekle
ALTER TABLE public.qlinik_content_domains DROP CONSTRAINT IF EXISTS qlinik_content_domains_code_check;
ALTER TABLE public.qlinik_content_domains ADD CONSTRAINT qlinik_content_domains_code_check
  CHECK (code IN ('tip','dis','eczacilik','hemsirelik','ebelik','saglik_bilimleri','meslek_onlisans','mezun','diger','ftr','veteriner'));

-- 2) Yeni disiplinler (kurulumda görünür)
INSERT INTO public.qlinik_content_domains (code, label_tr, default_target_exam, is_active) VALUES
  ('ftr','Fizik Tedavi ve Rehabilitasyon','FTR',true),
  ('veteriner','Veteriner Hekimliği','VUÇEP',true)
ON CONFLICT (code) DO NOTHING;

-- 3) Veteriner taksonomisi (253 ders→konu satırı)
INSERT INTO public.qlinik_taxonomy (discipline_code, subject, topic, subtopic, sort_order, is_active) VALUES
  ('veteriner','Medikal Fizik ve Temel Kimya','Medikal fizik temel kavramları','',0,true),
  ('veteriner','Medikal Fizik ve Temel Kimya','İnorganik kimya','',1,true),
  ('veteriner','Medikal Fizik ve Temel Kimya','Organik kimya','',2,true),
  ('veteriner','Medikal Fizik ve Temel Kimya','Laboratuvar güvenliği','',3,true),
  ('veteriner','Medikal Fizik ve Temel Kimya','Temel hesaplamalar','',4,true),
  ('veteriner','Hayvan Biyolojisi, Zooloji ve Hücre Biyolojisi','Hücre biyolojisi','',5,true),
  ('veteriner','Hayvan Biyolojisi, Zooloji ve Hücre Biyolojisi','Hayvanlar alemi ve sınıflandırma','',6,true),
  ('veteriner','Hayvan Biyolojisi, Zooloji ve Hücre Biyolojisi','Doku ve organ düzeyinde organizasyon','',7,true),
  ('veteriner','Hayvan Biyolojisi, Zooloji ve Hücre Biyolojisi','Üreme ve gelişim biyolojisi','',8,true),
  ('veteriner','Hayvan Biyolojisi, Zooloji ve Hücre Biyolojisi','Ekoloji ve yaşam döngüleri','',9,true),
  ('veteriner','Anatomi','Anatomik terminoloji','',10,true),
  ('veteriner','Anatomi','Hareket sistemi anatomisi','',11,true),
  ('veteriner','Anatomi','Sindirim sistemi anatomisi','',12,true),
  ('veteriner','Anatomi','Solunum ve dolaşım sistemi anatomisi','',13,true),
  ('veteriner','Anatomi','Ürogenital sistem anatomisi','',14,true),
  ('veteriner','Anatomi','Sinir sistemi ve duyu organları','',15,true),
  ('veteriner','Histoloji ve Embriyoloji','Temel dokular','',16,true),
  ('veteriner','Histoloji ve Embriyoloji','Kan ve lenfoid doku','',17,true),
  ('veteriner','Histoloji ve Embriyoloji','Organ histolojisi','',18,true),
  ('veteriner','Histoloji ve Embriyoloji','Üreme sistemi histolojisi','',19,true),
  ('veteriner','Histoloji ve Embriyoloji','Embriyolojik gelişim','',20,true),
  ('veteriner','Fizyoloji','Kan fizyolojisi','',21,true),
  ('veteriner','Fizyoloji','Kardiyovasküler fizyoloji','',22,true),
  ('veteriner','Fizyoloji','Solunum fizyolojisi','',23,true),
  ('veteriner','Fizyoloji','Sindirim ve rumen fizyolojisi','',24,true),
  ('veteriner','Fizyoloji','Böbrek ve sıvı-elektrolit dengesi','',25,true),
  ('veteriner','Fizyoloji','Endokrin ve üreme fizyolojisi','',26,true),
  ('veteriner','Biyokimya','Protein ve enzim biyokimyası','',27,true),
  ('veteriner','Biyokimya','Karbonhidrat metabolizması','',28,true),
  ('veteriner','Biyokimya','Lipit metabolizması','',29,true),
  ('veteriner','Biyokimya','Mineral ve vitamin biyokimyası','',30,true),
  ('veteriner','Biyokimya','Klinik biyokimya','',31,true),
  ('veteriner','Genetik ve Islahın Temelleri','Mendel genetiği','',32,true),
  ('veteriner','Genetik ve Islahın Temelleri','Moleküler genetik','',33,true),
  ('veteriner','Genetik ve Islahın Temelleri','Popülasyon genetiği','',34,true),
  ('veteriner','Genetik ve Islahın Temelleri','Kalıtsal hastalıklar','',35,true),
  ('veteriner','Genetik ve Islahın Temelleri','Genetik ıslah','',36,true),
  ('veteriner','Biyoistatistik ve Bilimsel Araştırma','Veri ve ölçüm','',37,true),
  ('veteriner','Biyoistatistik ve Bilimsel Araştırma','Hipotez testleri','',38,true),
  ('veteriner','Biyoistatistik ve Bilimsel Araştırma','Epidemiyolojik ölçütler','',39,true),
  ('veteriner','Biyoistatistik ve Bilimsel Araştırma','Araştırma tasarımları','',40,true),
  ('veteriner','Biyoistatistik ve Bilimsel Araştırma','Makale okuryazarlığı','',41,true),
  ('veteriner','Mesleki İletişim, Etik ve Profesyonellik','Veteriner hekimlik mesleği','',42,true),
  ('veteriner','Mesleki İletişim, Etik ve Profesyonellik','Hasta sahibi iletişimi','',43,true),
  ('veteriner','Mesleki İletişim, Etik ve Profesyonellik','Etik ilkeler','',44,true),
  ('veteriner','Mesleki İletişim, Etik ve Profesyonellik','Aydınlatılmış onam ve kayıt','',45,true),
  ('veteriner','Mesleki İletişim, Etik ve Profesyonellik','Hayvan refahı duyarlılığı','',46,true),
  ('veteriner','Mikrobiyoloji','Bakteri yapısı ve sınıflandırma','',47,true),
  ('veteriner','Mikrobiyoloji','Gram pozitif bakteriler','',48,true),
  ('veteriner','Mikrobiyoloji','Gram negatif bakteriler','',49,true),
  ('veteriner','Mikrobiyoloji','Özel bakteriler','',50,true),
  ('veteriner','Mikrobiyoloji','Mikrobiyolojik tanı','',51,true),
  ('veteriner','Viroloji','Virüs yapısı ve çoğalması','',52,true),
  ('veteriner','Viroloji','Solunum ve sistemik viral hastalıklar','',53,true),
  ('veteriner','Viroloji','Kanatlı viral hastalıkları','',54,true),
  ('veteriner','Viroloji','Zoonotik virüsler','',55,true),
  ('veteriner','Viroloji','Viral tanı ve aşılama','',56,true),
  ('veteriner','İmmünoloji','Doğal bağışıklık','',57,true),
  ('veteriner','İmmünoloji','Edinsel bağışıklık','',58,true),
  ('veteriner','İmmünoloji','Aşı immünolojisi','',59,true),
  ('veteriner','İmmünoloji','Hipersensitivite ve otoimmünite','',60,true),
  ('veteriner','İmmünoloji','Serolojik testler','',61,true),
  ('veteriner','Parazitoloji','Protozoonlar','',62,true),
  ('veteriner','Parazitoloji','Nematodlar','',63,true),
  ('veteriner','Parazitoloji','Trematod ve sestodlar','',64,true),
  ('veteriner','Parazitoloji','Ektoparazitler','',65,true),
  ('veteriner','Parazitoloji','Parazit kontrol programları','',66,true),
  ('veteriner','Patoloji','Hücre zedelenmesi','',67,true),
  ('veteriner','Patoloji','İnflamasyon ve onarım','',68,true),
  ('veteriner','Patoloji','Dolaşım bozuklukları','',69,true),
  ('veteriner','Patoloji','Neoplazi','',70,true),
  ('veteriner','Patoloji','Nekropsi ve örnekleme','',71,true),
  ('veteriner','Farmakoloji ve Farmakoterapi','Farmakokinetik','',72,true),
  ('veteriner','Farmakoloji ve Farmakoterapi','Farmakodinami','',73,true),
  ('veteriner','Farmakoloji ve Farmakoterapi','Antimikrobiyal ilaçlar','',74,true),
  ('veteriner','Farmakoloji ve Farmakoterapi','Analjezik ve antiinflamatuvarlar','',75,true),
  ('veteriner','Farmakoloji ve Farmakoterapi','İlaç kalıntısı ve arınma süresi','',76,true),
  ('veteriner','Toksikoloji','Toksikokinetik ve toksikodinami','',77,true),
  ('veteriner','Toksikoloji','Bitkisel ve yem kaynaklı zehirlenmeler','',78,true),
  ('veteriner','Toksikoloji','Pestisit ve ağır metal zehirlenmeleri','',79,true),
  ('veteriner','Toksikoloji','Küçük hayvan zehirlenmeleri','',80,true),
  ('veteriner','Toksikoloji','Zehirlenmelerde acil yaklaşım','',81,true),
  ('veteriner','Epidemiyoloji ve Biyogüvenlik','Hastalık ölçütleri','',82,true),
  ('veteriner','Epidemiyoloji ve Biyogüvenlik','Salgın araştırması','',83,true),
  ('veteriner','Epidemiyoloji ve Biyogüvenlik','Tanı testlerinin değerlendirilmesi','',84,true),
  ('veteriner','Epidemiyoloji ve Biyogüvenlik','Biyogüvenlik','',85,true),
  ('veteriner','Epidemiyoloji ve Biyogüvenlik','Hastalık kontrol programları','',86,true),
  ('veteriner','Klinik Laboratuvar ve Tanısal Testler','Hematoloji','',87,true),
  ('veteriner','Klinik Laboratuvar ve Tanısal Testler','Serum biyokimyası','',88,true),
  ('veteriner','Klinik Laboratuvar ve Tanısal Testler','İdrar ve dışkı analizleri','',89,true),
  ('veteriner','Klinik Laboratuvar ve Tanısal Testler','Sitoloji ve sıvı analizleri','',90,true),
  ('veteriner','Klinik Laboratuvar ve Tanısal Testler','Test seçimi ve hata kaynakları','',91,true),
  ('veteriner','Propedötik ve Klinik Muayene','Anamnez ve kayıt','',92,true),
  ('veteriner','Propedötik ve Klinik Muayene','Genel muayene','',93,true),
  ('veteriner','Propedötik ve Klinik Muayene','Sistem muayenesi','',94,true),
  ('veteriner','Propedötik ve Klinik Muayene','Sürü ve işletme muayenesi','',95,true),
  ('veteriner','Propedötik ve Klinik Muayene','Ayırıcı tanı mantığı','',96,true),
  ('veteriner','İç Hastalıkları','Solunum sistemi hastalıkları','',97,true),
  ('veteriner','İç Hastalıkları','Sindirim sistemi hastalıkları','',98,true),
  ('veteriner','İç Hastalıkları','Üriner ve endokrin hastalıklar','',99,true),
  ('veteriner','İç Hastalıkları','Kardiyovasküler ve hematolojik hastalıklar','',100,true),
  ('veteriner','İç Hastalıkları','Nörolojik ve dermatolojik hastalıklar','',101,true),
  ('veteriner','İç Hastalıkları','Metabolik ve sürü hastalıkları','',102,true),
  ('veteriner','Cerrahi','Cerrahi asepsi ve hazırlık','',103,true),
  ('veteriner','Cerrahi','Yara ve doku iyileşmesi','',104,true),
  ('veteriner','Cerrahi','Yumuşak doku cerrahisi','',105,true),
  ('veteriner','Cerrahi','Ortopedi ve travma','',106,true),
  ('veteriner','Cerrahi','Postoperatif bakım','',107,true),
  ('veteriner','Anesteziyoloji, Analjezi ve Acil Yaklaşım','Preanestezik değerlendirme','',108,true),
  ('veteriner','Anesteziyoloji, Analjezi ve Acil Yaklaşım','Genel ve lokal anestezi','',109,true),
  ('veteriner','Anesteziyoloji, Analjezi ve Acil Yaklaşım','Monitörizasyon','',110,true),
  ('veteriner','Anesteziyoloji, Analjezi ve Acil Yaklaşım','Ağrı yönetimi','',111,true),
  ('veteriner','Anesteziyoloji, Analjezi ve Acil Yaklaşım','Acil ve resüsitasyon','',112,true),
  ('veteriner','Doğum, Jinekoloji ve Reprodüksiyon','Üreme fizyolojisi ve siklus','',113,true),
  ('veteriner','Doğum, Jinekoloji ve Reprodüksiyon','Gebelik tanısı ve izlem','',114,true),
  ('veteriner','Doğum, Jinekoloji ve Reprodüksiyon','Güç doğum ve obstetrik müdahale','',115,true),
  ('veteriner','Doğum, Jinekoloji ve Reprodüksiyon','İnfertilite ve androloji','',116,true),
  ('veteriner','Doğum, Jinekoloji ve Reprodüksiyon','Meme sağlığı ve mastitis','',117,true),
  ('veteriner','Diagnostik Görüntüleme','Radyografi temel ilkeleri','',118,true),
  ('veteriner','Diagnostik Görüntüleme','Toraks ve abdomen radyolojisi','',119,true),
  ('veteriner','Diagnostik Görüntüleme','İskelet sistemi görüntüleme','',120,true),
  ('veteriner','Diagnostik Görüntüleme','Ultrasonografi','',121,true),
  ('veteriner','Diagnostik Görüntüleme','İleri görüntüleme','',122,true),
  ('veteriner','Dermatoloji, Oftalmoloji ve Kulak','Dermatolojik muayene','',123,true),
  ('veteriner','Dermatoloji, Oftalmoloji ve Kulak','Enfeksiyöz ve paraziter deri hastalıkları','',124,true),
  ('veteriner','Dermatoloji, Oftalmoloji ve Kulak','Oftalmolojik muayene','',125,true),
  ('veteriner','Dermatoloji, Oftalmoloji ve Kulak','Göz hastalıkları','',126,true),
  ('veteriner','Dermatoloji, Oftalmoloji ve Kulak','Kulak hastalıkları','',127,true),
  ('veteriner','Koruyucu Hekimlik ve Aşılama','Koruyucu hekimlik ilkeleri','',128,true),
  ('veteriner','Koruyucu Hekimlik ve Aşılama','Küçük hayvan aşılama','',129,true),
  ('veteriner','Koruyucu Hekimlik ve Aşılama','Çiftlik hayvanlarında koruma','',130,true),
  ('veteriner','Koruyucu Hekimlik ve Aşılama','Zoonozlardan korunma','',131,true),
  ('veteriner','Koruyucu Hekimlik ve Aşılama','Hasta sahibi ve yetiştirici eğitimi','',132,true),
  ('veteriner','Kedi ve Köpek Hekimliği','Koruyucu hekimlik ve pediatri','',133,true),
  ('veteriner','Kedi ve Köpek Hekimliği','Kedi-köpek enfeksiyon hastalıkları','',134,true),
  ('veteriner','Kedi ve Köpek Hekimliği','Küçük hayvan iç hastalıkları','',135,true),
  ('veteriner','Kedi ve Köpek Hekimliği','Küçük hayvan acil ve kritik bakım','',136,true),
  ('veteriner','Kedi ve Köpek Hekimliği','Davranış ve geriatrik hasta','',137,true),
  ('veteriner','Sığır Hekimliği','Buzağı sağlığı','',138,true),
  ('veteriner','Sığır Hekimliği','Süt sığırı metabolik hastalıkları','',139,true),
  ('veteriner','Sığır Hekimliği','Meme sağlığı','',140,true),
  ('veteriner','Sığır Hekimliği','Ayak ve topallık','',141,true),
  ('veteriner','Sığır Hekimliği','Reprodüksiyon ve sürü performansı','',142,true),
  ('veteriner','Koyun ve Keçi Hekimliği','Kuzu-oğlak hastalıkları','',143,true),
  ('veteriner','Koyun ve Keçi Hekimliği','Abort ve reprodüktif hastalıklar','',144,true),
  ('veteriner','Koyun ve Keçi Hekimliği','Paraziter hastalıklar','',145,true),
  ('veteriner','Koyun ve Keçi Hekimliği','Solunum ve sindirim hastalıkları','',146,true),
  ('veteriner','Koyun ve Keçi Hekimliği','Sürü yönetimi','',147,true),
  ('veteriner','At Hekimliği','Atlarda klinik muayene','',148,true),
  ('veteriner','At Hekimliği','Kolik ve sindirim hastalıkları','',149,true),
  ('veteriner','At Hekimliği','Solunum ve enfeksiyon hastalıkları','',150,true),
  ('veteriner','At Hekimliği','Topallık ve spor atı hekimliği','',151,true),
  ('veteriner','At Hekimliği','Reprodüksiyon ve tay sağlığı','',152,true),
  ('veteriner','Kanatlı Hekimliği','Kanatlı anatomisi ve fizyolojisi','',153,true),
  ('veteriner','Kanatlı Hekimliği','Viral hastalıklar','',154,true),
  ('veteriner','Kanatlı Hekimliği','Bakteriyel ve paraziter hastalıklar','',155,true),
  ('veteriner','Kanatlı Hekimliği','Sürü performansı','',156,true),
  ('veteriner','Kanatlı Hekimliği','Biyogüvenlik ve aşılama','',157,true),
  ('veteriner','Su Ürünleri Hekimliği','Balık anatomisi ve fizyolojisi','',158,true),
  ('veteriner','Su Ürünleri Hekimliği','Su kalitesi','',159,true),
  ('veteriner','Su Ürünleri Hekimliği','Balık hastalıkları','',160,true),
  ('veteriner','Su Ürünleri Hekimliği','Tedavi ve koruma','',161,true),
  ('veteriner','Su Ürünleri Hekimliği','Akuakültür biyogüvenliği','',162,true),
  ('veteriner','Arı Hekimliği','Arı biyolojisi','',163,true),
  ('veteriner','Arı Hekimliği','Koloni yönetimi','',164,true),
  ('veteriner','Arı Hekimliği','Bakteriyel ve fungal hastalıklar','',165,true),
  ('veteriner','Arı Hekimliği','Paraziter ve viral sorunlar','',166,true),
  ('veteriner','Arı Hekimliği','Pestisit ve çevresel riskler','',167,true),
  ('veteriner','Egzotik ve Yaban Hayvanları','Yakalama ve tespit','',168,true),
  ('veteriner','Egzotik ve Yaban Hayvanları','Kuş ve sürüngen hastalıkları','',169,true),
  ('veteriner','Egzotik ve Yaban Hayvanları','Küçük memeli egzotikler','',170,true),
  ('veteriner','Egzotik ve Yaban Hayvanları','Yaban hayatı rehabilitasyonu','',171,true),
  ('veteriner','Egzotik ve Yaban Hayvanları','Mevzuat ve etik','',172,true),
  ('veteriner','Laboratuvar ve Deney Hayvanları','Deney hayvanı biyolojisi','',173,true),
  ('veteriner','Laboratuvar ve Deney Hayvanları','Barındırma ve refah','',174,true),
  ('veteriner','Laboratuvar ve Deney Hayvanları','Anestezi ve ötenazi','',175,true),
  ('veteriner','Laboratuvar ve Deney Hayvanları','Deneysel enfeksiyon ve biyogüvenlik','',176,true),
  ('veteriner','Laboratuvar ve Deney Hayvanları','3R ilkeleri','',177,true),
  ('veteriner','Zootekni ve Hayvan Islahı','Evcil hayvan türleri ve ırklar','',178,true),
  ('veteriner','Zootekni ve Hayvan Islahı','Verim özellikleri','',179,true),
  ('veteriner','Zootekni ve Hayvan Islahı','Seleksiyon ve melezleme','',180,true),
  ('veteriner','Zootekni ve Hayvan Islahı','Kayıt ve soy kütüğü','',181,true),
  ('veteriner','Zootekni ve Hayvan Islahı','Genetik ilerleme ve riskler','',182,true),
  ('veteriner','Hayvan Besleme','Besin maddeleri','',183,true),
  ('veteriner','Hayvan Besleme','Ruminant besleme','',184,true),
  ('veteriner','Hayvan Besleme','Tek mideli hayvan besleme','',185,true),
  ('veteriner','Hayvan Besleme','Kanatlı besleme','',186,true),
  ('veteriner','Hayvan Besleme','Beslenme hastalıkları','',187,true),
  ('veteriner','Yem Bilgisi ve Yem Hijyeni','Kaba ve kesif yemler','',188,true),
  ('veteriner','Yem Bilgisi ve Yem Hijyeni','Yem analizi','',189,true),
  ('veteriner','Yem Bilgisi ve Yem Hijyeni','Yem katkıları','',190,true),
  ('veteriner','Yem Bilgisi ve Yem Hijyeni','Yem kontaminasyonu','',191,true),
  ('veteriner','Yem Bilgisi ve Yem Hijyeni','Rasyon hazırlama','',192,true),
  ('veteriner','Hayvan Refahı ve Etoloji','Davranışın temelleri','',193,true),
  ('veteriner','Hayvan Refahı ve Etoloji','Refah göstergeleri','',194,true),
  ('veteriner','Hayvan Refahı ve Etoloji','Çiftlik hayvanlarında refah','',195,true),
  ('veteriner','Hayvan Refahı ve Etoloji','Pet hayvanlarında refah','',196,true),
  ('veteriner','Hayvan Refahı ve Etoloji','Refah mevzuatı ve denetim','',197,true),
  ('veteriner','Sürü Sağlığı ve İşletme Yönetimi','Sürü kayıtları','',198,true),
  ('veteriner','Sürü Sağlığı ve İşletme Yönetimi','Performans göstergeleri','',199,true),
  ('veteriner','Sürü Sağlığı ve İşletme Yönetimi','Sürü sağlık programları','',200,true),
  ('veteriner','Sürü Sağlığı ve İşletme Yönetimi','İşletme biyogüvenliği','',201,true),
  ('veteriner','Sürü Sağlığı ve İşletme Yönetimi','Ekonomik kararlar','',202,true),
  ('veteriner','Hayvansal Üretim ve Verim','Süt üretimi','',203,true),
  ('veteriner','Hayvansal Üretim ve Verim','Et üretimi','',204,true),
  ('veteriner','Hayvansal Üretim ve Verim','Yumurta ve kanatlı üretimi','',205,true),
  ('veteriner','Hayvansal Üretim ve Verim','Üreme verimi','',206,true),
  ('veteriner','Hayvansal Üretim ve Verim','Sürdürülebilir üretim','',207,true),
  ('veteriner','Barınak Hijyeni ve Çevre Yönetimi','Barınak tasarımı','',208,true),
  ('veteriner','Barınak Hijyeni ve Çevre Yönetimi','Hijyen ve dezenfeksiyon','',209,true),
  ('veteriner','Barınak Hijyeni ve Çevre Yönetimi','Atık ve gübre yönetimi','',210,true),
  ('veteriner','Barınak Hijyeni ve Çevre Yönetimi','İklim ve stres yönetimi','',211,true),
  ('veteriner','Barınak Hijyeni ve Çevre Yönetimi','Barınak kaynaklı hastalık riskleri','',212,true),
  ('veteriner','Gıda Hijyeni ve Teknolojisi','Gıda mikrobiyolojisi','',213,true),
  ('veteriner','Gıda Hijyeni ve Teknolojisi','HACCP ve risk analizi','',214,true),
  ('veteriner','Gıda Hijyeni ve Teknolojisi','Gıda işleme teknolojileri','',215,true),
  ('veteriner','Gıda Hijyeni ve Teknolojisi','Gıda katkıları ve kalıntılar','',216,true),
  ('veteriner','Gıda Hijyeni ve Teknolojisi','Gıda kaynaklı salgınlar','',217,true),
  ('veteriner','Et Hijyeni ve Kesimhane','Ante-mortem muayene','',218,true),
  ('veteriner','Et Hijyeni ve Kesimhane','Post-mortem muayene','',219,true),
  ('veteriner','Et Hijyeni ve Kesimhane','Kesimhane hijyeni','',220,true),
  ('veteriner','Et Hijyeni ve Kesimhane','Karkas kararları','',221,true),
  ('veteriner','Et Hijyeni ve Kesimhane','Et kaynaklı zoonozlar','',222,true),
  ('veteriner','Süt ve Süt Ürünleri Hijyeni','Çiğ süt hijyeni','',223,true),
  ('veteriner','Süt ve Süt Ürünleri Hijyeni','Sağım hijyeni','',224,true),
  ('veteriner','Süt ve Süt Ürünleri Hijyeni','Süt işleme teknolojisi','',225,true),
  ('veteriner','Süt ve Süt Ürünleri Hijyeni','Süt kaynaklı patojenler','',226,true),
  ('veteriner','Süt ve Süt Ürünleri Hijyeni','Kalite kontrol','',227,true),
  ('veteriner','Veteriner Halk Sağlığı ve Zoonozlar','Tek sağlık yaklaşımı','',228,true),
  ('veteriner','Veteriner Halk Sağlığı ve Zoonozlar','Bakteriyel zoonozlar','',229,true),
  ('veteriner','Veteriner Halk Sağlığı ve Zoonozlar','Viral zoonozlar','',230,true),
  ('veteriner','Veteriner Halk Sağlığı ve Zoonozlar','Paraziter zoonozlar','',231,true),
  ('veteriner','Veteriner Halk Sağlığı ve Zoonozlar','Zoonoz kontrolü','',232,true),
  ('veteriner','Resmi Kontroller ve Denetim','Resmi veteriner hekimlik','',233,true),
  ('veteriner','Resmi Kontroller ve Denetim','Hayvan hareketleri','',234,true),
  ('veteriner','Resmi Kontroller ve Denetim','Bildirimi zorunlu hastalıklar','',235,true),
  ('veteriner','Resmi Kontroller ve Denetim','Gıda işletmesi denetimi','',236,true),
  ('veteriner','Resmi Kontroller ve Denetim','Salgın ve kriz yönetimi','',237,true),
  ('veteriner','Veteriner Mevzuatı ve İlaç Kullanımı','Meslek mevzuatı','',238,true),
  ('veteriner','Veteriner Mevzuatı ve İlaç Kullanımı','Reçete ve ilaç uygulamaları','',239,true),
  ('veteriner','Veteriner Mevzuatı ve İlaç Kullanımı','Hayvan refahı mevzuatı','',240,true),
  ('veteriner','Veteriner Mevzuatı ve İlaç Kullanımı','Kimliklendirme ve kayıt','',241,true),
  ('veteriner','Veteriner Mevzuatı ve İlaç Kullanımı','Malpraktis ve mesleki sorumluluk','',242,true),
  ('veteriner','Adli Veterinerlik','Adli olgu yaklaşımı','',243,true),
  ('veteriner','Adli Veterinerlik','Hayvan istismarı ve ihmali','',244,true),
  ('veteriner','Adli Veterinerlik','Adli nekropsi','',245,true),
  ('veteriner','Adli Veterinerlik','Bilirkişilik','',246,true),
  ('veteriner','Adli Veterinerlik','Vahşi yaşam ve kaçakçılık','',247,true),
  ('veteriner','Afetlerde Veteriner Hekimliği','Afet hazırlığı','',248,true),
  ('veteriner','Afetlerde Veteriner Hekimliği','Sahada triyaj','',249,true),
  ('veteriner','Afetlerde Veteriner Hekimliği','Salgın ve biyogüvenlik','',250,true),
  ('veteriner','Afetlerde Veteriner Hekimliği','Gıda ve su güvenliği','',251,true),
  ('veteriner','Afetlerde Veteriner Hekimliği','Afet sonrası rehabilitasyon','',252,true);
